name: Publish

on: 
  workflow_dispatch: 
  push: 
    branches:
    - release
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./BankApi.sln

    - name: Build
      run: dotnet build ./BankApi.sln --configuration Release
      
    - name: Publish
      run: dotnet publish ./BankApi/BankApi.csproj --configuration Release --no-build --output ./publish
    
    - name: Deployment
      uses: azure/webapps-deploy@v2
      with: 
        app-name: bankapi
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './publish'
